package com.pulse.scorer;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import com.pulse.common.config.ScoringProperties;
import com.pulse.common.message.ScoreTask;
import com.pulse.domain.Game;
import com.pulse.domain.GameEvent;
import com.pulse.domain.GameEventRepository;
import com.pulse.domain.GameRepository;
import com.pulse.domain.Play;
import com.pulse.domain.PlayRepository;
import com.pulse.domain.WatchScore;
import com.pulse.domain.WatchScoreRepository;
import com.pulse.scoring.ImportanceCalculator;
import com.pulse.scoring.ScoreCalculator;
import com.pulse.scoring.ScoringInput;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.context.event.EventListener;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@DataJpaTest
@Import({
        LiveScoringService.class,
        GameEventExtractor.class,
        TimelineHighlightTrigger.class,
        GameEventCopyCommitListener.class,
        LiveScoringTransactionBoundaryTest.Config.class
})
@TestPropertySource(properties = {
        "spring.flyway.enabled=false",
        "pulse.scorer.enabled=true"
})
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class LiveScoringTransactionBoundaryTest {

    private static final long COMMIT_GAME_ID = 5059041L;
    private static final long ROLLBACK_GAME_ID = 5059042L;
    private static final Instant OBSERVED_AT = Instant.parse("2026-07-21T01:00:00Z");

    @Autowired
    private LiveScoringService liveScoringService;

    @Autowired
    private GameRepository gameRepository;

    @Autowired
    private PlayRepository playRepository;

    @Autowired
    private WatchScoreRepository watchScoreRepository;

    @Autowired
    private GameEventRepository gameEventRepository;

    @Autowired
    private RollbackProbe rollbackProbe;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockitoBean
    private ScoreCalculator scoreCalculator;

    @MockitoBean
    private ImportanceCalculator importanceCalculator;

    @MockitoBean
    private LiveSignalPublisher liveSignalPublisher;

    @MockitoBean
    private AiGenerationTrigger aiGenerationTrigger;

    @BeforeEach
    void ensureH2WatchScoreTable() {
        // H2는 엔티티의 PostgreSQL 전용 text[] DDL을 해석하지 못하므로 테스트용 호환 테이블을 만든다.
        jdbcTemplate.execute("""
                create table if not exists watch_scores (
                    id bigint generated by default as identity primary key,
                    backfilled boolean,
                    base_score integer,
                    computed_at timestamp with time zone,
                    game_id bigint not null,
                    importance_multiplier numeric(38,2),
                    inning integer,
                    inning_type varchar(255),
                    play_order bigint,
                    pregame_bonus numeric(38,2),
                    scoring_version integer,
                    signal_contributions json,
                    source varchar(255),
                    tags varchar array,
                    watch_score integer
                )
                """);
    }

    @Test
    void handle_shouldCommitWatchScoreGameEventAndHighlightTogetherBeforeAiRequest() {
        prepareLiveCycle(COMMIT_GAME_ID);

        liveScoringService.handle(liveTask(COMMIT_GAME_ID));

        assertThat(watchScoreRepository.findByGameIdOrderByComputedAtAsc(COMMIT_GAME_ID)).hasSize(2);
        List<GameEvent> events = gameEventRepository
                .findByGameIdAndSpoilerLevelOrderByObservedAtAscIdAsc(
                        COMMIT_GAME_ID, GameEvent.SPOILER_PROTECTED_SAFE);
        assertThat(events).singleElement().satisfies(event -> {
            assertThat(event.getEventType()).isEqualTo(GameEventExtractor.EVENT_PRESSURE_BASES_LOADED);
            assertThat(event.isTimelineHighlight()).isTrue();
            verify(aiGenerationTrigger).onGameEventPersisted(
                    COMMIT_GAME_ID,
                    event.getId(),
                    AiGenerationTrigger.MODE_PROTECTED,
                    OBSERVED_AT);
        });
    }

    @Test
    void handle_shouldRollbackWatchScoreGameEventAndHighlightWhenLateTransactionStepFails() {
        prepareLiveCycle(ROLLBACK_GAME_ID);
        rollbackProbe.failNext = true;

        assertThatThrownBy(() -> liveScoringService.handle(liveTask(ROLLBACK_GAME_ID)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("트랜잭션 롤백 검증");

        assertThat(watchScoreRepository.findByGameIdOrderByComputedAtAsc(ROLLBACK_GAME_ID)).hasSize(1);
        assertThat(gameEventRepository.findByGameIdAndSpoilerLevelOrderByObservedAtAscIdAsc(
                ROLLBACK_GAME_ID, GameEvent.SPOILER_PROTECTED_SAFE)).isEmpty();
        assertThat(gameRepository.findById(ROLLBACK_GAME_ID).orElseThrow().getPeakBaseScore()).isNull();
        verifyNoInteractions(aiGenerationTrigger);
    }

    private void prepareLiveCycle(long gameId) {
        Game game = new Game();
        game.setId(gameId);
        game.setStatus(Game.STATUS_IN_PROGRESS);
        game.setLifecycleState("LIVE");
        game.setPeriod(8);
        game.setHomeRuns(3);
        game.setAwayRuns(2);
        gameRepository.save(game);

        Play play = new Play();
        play.setGameId(gameId);
        play.setPlayOrder(100L);
        play.setType("at_bat");
        play.setInning(8);
        play.setInningType("Top");
        play.setHomeScore(3);
        play.setAwayScore(2);
        play.setScoringPlay(false);
        play.setOuts(1);
        play.setBalls(0);
        play.setStrikes(0);
        play.setBatterId(10L);
        play.setPitcherId(20L);
        play.setFetchedAt(OBSERVED_AT);
        play.setRunnerOnFirst(true);
        play.setRunnerOnSecond(true);
        play.setRunnerOnThird(true);
        playRepository.save(play);

        WatchScore baseline = new WatchScore();
        baseline.setGameId(gameId);
        baseline.setComputedAt(OBSERVED_AT.minusSeconds(60));
        baseline.setPlayOrder(99L);
        baseline.setInning(8);
        baseline.setInningType("Top");
        baseline.setBaseScore(30);
        baseline.setImportanceMultiplier(BigDecimal.ONE);
        baseline.setPregameBonus(BigDecimal.ZERO);
        baseline.setWatchScore(40);
        baseline.setScoringVersion(5);
        baseline.setSignalContributions(Map.of());
        baseline.setTags(List.of());
        baseline.setBackfilled(false);
        baseline.setSource("OPERATIONAL");
        watchScoreRepository.save(baseline);

        when(importanceCalculator.multiplier(any(Game.class))).thenReturn(1.0);
        when(scoreCalculator.calculate(any(ScoringInput.class)))
                .thenReturn(new ScoreCalculator.Result(Map.of(), 60.0, false, 1.0, 0, 80.0));
    }

    private static ScoreTask liveTask(long gameId) {
        return new ScoreTask(gameId, OBSERVED_AT, 100L, "LIVE", null);
    }

    @TestConfiguration
    static class Config {

        @Bean
        ScoringProperties scoringProperties() {
            return TestScoringProperties.version5(
                    new ScoringProperties.Highlight(true, 40, 12, 6, 8, 8));
        }

        @Bean
        RollbackProbe rollbackProbe() {
            return new RollbackProbe();
        }
    }

    static class RollbackProbe {
        boolean failNext;

        @EventListener
        void onLiveScoreComputed(LiveScoreComputedEvent event) {
            if (failNext) {
                failNext = false;
                throw new IllegalStateException("트랜잭션 롤백 검증");
            }
        }
    }
}
