INSERT INTO teams (
    team_id,
    logo_team_id,
    abbreviation,
    display_name,
    short_display_name,
    name,
    location,
    slug,
    league,
    division
)
VALUES
    (1, 109, 'ARI', 'Arizona Diamondbacks', 'Diamondbacks', 'Diamondbacks', 'Arizona', 'arizona-diamondbacks', 'National', 'West'),
    (2, 144, 'ATL', 'Atlanta Braves', 'Braves', 'Braves', 'Atlanta', 'atlanta-braves', 'National', 'East'),
    (3, 110, 'BAL', 'Baltimore Orioles', 'Orioles', 'Orioles', 'Baltimore', 'baltimore-orioles', 'American', 'East'),
    (4, 111, 'BOS', 'Boston Red Sox', 'Red Sox', 'Red Sox', 'Boston', 'boston-red-sox', 'American', 'East'),
    (5, 112, 'CHC', 'Chicago Cubs', 'Cubs', 'Cubs', 'Chicago', 'chicago-cubs', 'National', 'Central'),
    (6, 145, 'CHW', 'Chicago White Sox', 'White Sox', 'White Sox', 'Chicago', 'chicago-white-sox', 'American', 'Central'),
    (7, 113, 'CIN', 'Cincinnati Reds', 'Reds', 'Reds', 'Cincinnati', 'cincinnati-reds', 'National', 'Central'),
    (8, 114, 'CLE', 'Cleveland Guardians', 'Guardians', 'Guardians', 'Cleveland', 'cleveland-guardians', 'American', 'Central'),
    (9, 115, 'COL', 'Colorado Rockies', 'Rockies', 'Rockies', 'Colorado', 'colorado-rockies', 'National', 'West'),
    (10, 116, 'DET', 'Detroit Tigers', 'Tigers', 'Tigers', 'Detroit', 'detroit-tigers', 'American', 'Central'),
    (11, 117, 'HOU', 'Houston Astros', 'Astros', 'Astros', 'Houston', 'houston-astros', 'American', 'West'),
    (12, 118, 'KC', 'Kansas City Royals', 'Royals', 'Royals', 'Kansas City', 'kansas-city-royals', 'American', 'Central'),
    (13, 108, 'LAA', 'Los Angeles Angels', 'Angels', 'Angels', 'Los Angeles', 'los-angeles-angels', 'American', 'West'),
    (14, 119, 'LAD', 'Los Angeles Dodgers', 'Dodgers', 'Dodgers', 'Los Angeles', 'los-angeles-dodgers', 'National', 'West'),
    (15, 146, 'MIA', 'Miami Marlins', 'Marlins', 'Marlins', 'Miami', 'miami-marlins', 'National', 'East'),
    (16, 158, 'MIL', 'Milwaukee Brewers', 'Brewers', 'Brewers', 'Milwaukee', 'milwaukee-brewers', 'National', 'Central'),
    (17, 142, 'MIN', 'Minnesota Twins', 'Twins', 'Twins', 'Minnesota', 'minnesota-twins', 'American', 'Central'),
    (18, 121, 'NYM', 'New York Mets', 'Mets', 'Mets', 'New York', 'new-york-mets', 'National', 'East'),
    (19, 147, 'NYY', 'New York Yankees', 'Yankees', 'Yankees', 'New York', 'new-york-yankees', 'American', 'East'),
    (20, 133, 'OAK', 'Athletics', 'Athletics', 'Athletics', 'Oakland', 'oakland-athletics', 'American', 'West'),
    (21, 143, 'PHI', 'Philadelphia Phillies', 'Phillies', 'Phillies', 'Philadelphia', 'philadelphia-phillies', 'National', 'East'),
    (22, 134, 'PIT', 'Pittsburgh Pirates', 'Pirates', 'Pirates', 'Pittsburgh', 'pittsburgh-pirates', 'National', 'Central'),
    (23, 135, 'SD', 'San Diego Padres', 'Padres', 'Padres', 'San Diego', 'san-diego-padres', 'National', 'West'),
    (24, 137, 'SF', 'San Francisco Giants', 'Giants', 'Giants', 'San Francisco', 'san-francisco-giants', 'National', 'West'),
    (25, 136, 'SEA', 'Seattle Mariners', 'Mariners', 'Mariners', 'Seattle', 'seattle-mariners', 'American', 'West'),
    (26, 138, 'STL', 'St. Louis Cardinals', 'Cardinals', 'Cardinals', 'St. Louis', 'st-louis-cardinals', 'National', 'Central'),
    (27, 139, 'TB', 'Tampa Bay Rays', 'Rays', 'Rays', 'Tampa Bay', 'tampa-bay-rays', 'American', 'East'),
    (28, 140, 'TEX', 'Texas Rangers', 'Rangers', 'Rangers', 'Texas', 'texas-rangers', 'American', 'West'),
    (29, 141, 'TOR', 'Toronto Blue Jays', 'Blue Jays', 'Blue Jays', 'Toronto', 'toronto-blue-jays', 'American', 'East'),
    (30, 120, 'WSH', 'Washington Nationals', 'Nationals', 'Nationals', 'Washington', 'washington-nationals', 'National', 'East')
    ON CONFLICT (team_id) DO UPDATE SET
    logo_team_id = EXCLUDED.logo_team_id,
                                 abbreviation = EXCLUDED.abbreviation,
                                 display_name = EXCLUDED.display_name,
                                 short_display_name = EXCLUDED.short_display_name,
                                 name = EXCLUDED.name,
                                 location = EXCLUDED.location,
                                 slug = EXCLUDED.slug,
                                 league = EXCLUDED.league,
                                 division = EXCLUDED.division;